/**
 * API client for communicating with the backend worker
 * 
 * Supports both Service Bindings (production) and HTTP fetch (dev/fallback)
 */

import { getCloudflareContext } from '@opennextjs/cloudflare';
import type { ChatRequest, ChatResponse, ErrorResponse, WorkerMessage } from '@/types/chat';

const WORKER_URL = process.env.NEXT_PUBLIC_WORKER_URL || 'http://localhost:8787';

/**
 * Send a chat message to the backend worker
 * 
 * Uses Service Binding if available (production), otherwise falls back to HTTP fetch
 * 
 * @param sessionId - Unique session identifier
 * @param messages - Array of messages in worker format
 * @returns Promise resolving to chat response
 * @throws Error if request fails
 */
export async function sendChatMessage(
  sessionId: string,
  messages: WorkerMessage[]
): Promise<ChatResponse> {
  const requestBody: ChatRequest = {
    sessionId,
    messages,
  };

  try {
    // Try to use service binding first (production)
    const context = getCloudflareContext();
    // Type assertion for service binding (types generated by wrangler)
    const backend = (context?.env as { BACKEND?: Fetcher })?.BACKEND;

    let response: Response;

    if (backend) {
      // Use service binding for internal communication
      response = await backend.fetch('/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });
    } else {
      // Fallback to HTTP fetch (local development or when binding unavailable)
      response = await fetch(`${WORKER_URL}/chat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });
    }

    const data = await response.json();

    if (!response.ok) {
      const error = data as ErrorResponse;
      throw new Error(error.message || `Request failed with status ${response.status}`);
    }

    return data as ChatResponse;
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    throw new Error('Failed to send chat message');
  }
}

