import { getCloudflareContext } from '@opennextjs/cloudflare';
import type { ChatRequest, ChatResponse, ErrorResponse } from '@/types/chat';

const WORKER_URL = process.env.NEXT_PUBLIC_WORKER_URL || 'http://localhost:8787';

/**
 * POST /api/chat
 *
 * Server-side API route that handles chat messages to the backend worker.
 * Uses Cloudflare service bindings in production, falls back to HTTP in development.
 */
export async function POST(request: Request): Promise<Response> {
  try {
    const body: ChatRequest = await request.json();
    const { sessionId, messages } = body;

    // Try to use service binding first (production)
    let backend: Fetcher | undefined;
    try {
      const context = getCloudflareContext();
      // Type assertion for service binding (types generated by wrangler)
      backend = (context?.env as { BACKEND?: Fetcher })?.BACKEND;
    } catch {
      // getCloudflareContext() not available (e.g., during build or not initialized)
      // Will fallback to HTTP fetch
    }

    let response: Response;

    if (backend) {
      // Use service binding for internal communication
      response = await backend.fetch('/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ sessionId, messages }),
      });
    } else {
      // Fallback to HTTP fetch (local development or when binding unavailable)
      response = await fetch(`${WORKER_URL}/chat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ sessionId, messages }),
      });
    }

    const data = await response.json();

    if (!response.ok) {
      const error = data as ErrorResponse;
      return Response.json(
        { code: error.code, message: error.message },
        { status: response.status },
      );
    }

    return Response.json(data as ChatResponse);
  } catch (error) {
    return Response.json(
      {
        code: 'INTERNAL_ERROR',
        message: error instanceof Error ? error.message : 'Failed to send chat message',
      },
      { status: 500 },
    );
  }
}
